/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import static forms.appointment.pending_table;
import static forms.dashboard.ongoing_table1;
import static forms.dashboard.pending_table1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jake Marson Nable
 */
public class add_appointment extends javax.swing.JFrame {

    private static final String username = "root" ;
    private static final String password = "1234" ;
    private static final String dataconn = "jdbc:mysql://127.0.0.1:3306/workjob" ; 

   
   
    
    Connection sql = null;
    PreparedStatement pst  = null;
    ResultSet rs = null;
    int q, i;
   
   
     DefaultTableModel model;
   
    public add_appointment() {
        initComponents();
    }
    public void UpdateDb() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection sql = DriverManager.getConnection(dataconn, username, password);
            PreparedStatement pst = sql.prepareStatement("select * from workjob");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData stdata = rs.getMetaData();
            int q = stdata.getColumnCount();

            DefaultTableModel RecordTable1 = (DefaultTableModel) pending_table.getModel();
            DefaultTableModel RecordTable2 = (DefaultTableModel) pending_table1.getModel();
            DefaultTableModel RecordTable3 = (DefaultTableModel) ongoing_table1.getModel();
            RecordTable1.setRowCount(0);
            RecordTable2.setRowCount(0);
            RecordTable3.setRowCount(0);

            while (rs.next()) {
                Vector<Object> columnData1 = new Vector<>();
                Vector<Object> columnData2 = new Vector<>();
                Vector<Object> columnData3 = new Vector<>();

                // Add data to the first table
                columnData1.add(rs.getString("check_in"));
                columnData1.add(rs.getString("Time"));
                columnData1.add(rs.getString("Customer_name"));
                columnData1.add(rs.getString("Service_rendered"));
                columnData1.add(rs.getString("Price"));
                columnData1.add(rs.getString("Employee_Assigned"));
                RecordTable1.addRow(columnData1);

                // Add data to the second table
                columnData2.add(rs.getString("check_in"));
                columnData2.add(rs.getString("Time"));
                columnData2.add(rs.getString("Customer_name"));
                columnData2.add(rs.getString("Service_rendered"));
                columnData2.add(rs.getString("Price"));
                columnData2.add(rs.getString("Employee_Assigned"));
                RecordTable2.addRow(columnData2);

                // Add data to the third table
                columnData3.add(rs.getString("check_in"));
                columnData3.add(rs.getString("Time"));
                columnData3.add(rs.getString("Customer_name"));
                columnData3.add(rs.getString("Service_rendered"));
                columnData3.add(rs.getString("Price"));
                columnData3.add(rs.getString("Employee_Assigned"));
                RecordTable3.addRow(columnData3);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        done = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Checked in");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel1.add(txtCheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 30));
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 130, 30));

        jLabel2.setText("Time");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        txtcstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcstnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtcstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 30));

        jLabel3.setText("Customer Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel1.add(txtsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 30));

        jLabel4.setText("Service Rendered");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        jPanel1.add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));
        jPanel1.add(txtea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, 30));

        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel6.setText("Employee Assigned");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection sql = DriverManager.getConnection(dataconn, username, password);
    PreparedStatement pst = sql.prepareStatement("INSERT INTO workjob (check_in, Time, Customer_name, Service_rendered,Price,Employee_Assigned) VALUES (?,?,?,?,?,?) ");
    
    
    String name = txtCheckin.getText();
    String work = txtTime.getText();
    String assignedEmployee = txtcstname.getText();
    String serviceRendered = txtsr.getText();
    String price = txtprice.getText();
    String employee = txtea.getText();
    
    
    
    
    if(name == null || work == null || assignedEmployee == null || serviceRendered == null || price == null || employee == null) {
       
        JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    pst.setString(1, name);
    pst.setString(2, work);
    pst.setString(3, assignedEmployee);
    pst.setString(4, serviceRendered);
    pst.setString(5, price);
    pst.setString(6, employee);
    
    pst.executeUpdate();
    
    JOptionPane.showMessageDialog(this, "Record Added");
    UpdateDb();
    
    dispose();
          
} catch (ClassNotFoundException ex) { // Log the exception
            // Log the exception
    JOptionPane.showMessageDialog(this, "Database driver not found", "Error", JOptionPane.ERROR_MESSAGE);
} catch (SQLException ex) { // Log the exception
            // Log the exception
    JOptionPane.showMessageDialog(this, "Error inserting record: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        
        
        
    
    }//GEN-LAST:event_doneActionPerformed

    private void txtcstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcstnameActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_appointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton done;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static final javax.swing.JTextField txtCheckin = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtTime = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtcstname = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtea = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtprice = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtsr = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
